# Generated by Django 2.1.5 on 2019-01-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_admin_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='status',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
