# Generated by Django 2.1.5 on 2019-01-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_services_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='status',
            field=models.CharField(default='P', max_length=2),
        ),
    ]
